### ISSUE TITLE
Error during Ci/CD

### ISSUE THREAD

**Issue by beeyev** [vaimo/composer-patches#100]
Do you have any Ideas, why i get this error?

```shell
> pre-autoload-dump: Vaimo\ComposerPatches\Plugin->postInstall
Processing patches configuration
  - Removing league/fractal (0.19.2)
Executing async command (CWD): rm -rf '/builds/builder/backend/vendor/league/fractal'
  - Downloading league/fractal (0.19.2)
Downloading https:/api.github.com/repos/thephpleague/fractal/zipball/06dc15f6ba38f2dde2f919d3095d13b571190a7c
  - Installing league/fractal (0.19.2): Extracting archive
Executing async command (CWD): '/usr/bin/unzip' -qq '/builds/builder/backend/vendor/composer/tmp-d28b9e921dd7aa5a20cb8b543f1f5182' -d '/builds/builder/backend/vendor/composer/5915b398'
Executing command (CWD): rm -rf '/builds/builder/backend/vendor/composer/5915b398'
Executing command (CWD): rm -rf '/builds/builder/backend/vendor/league/fractal'
[302] https:/api.github.com/repos/thephpleague/fractal/zipball/06dc15f6ba38f2dde2f919d3095d13b571190a7c
Following redirect (1) https:/codeload.github.com/thephpleague/fractal/legacy.zip/06dc15f6ba38f2dde2f919d3095d13b571190a7c
[200] https:/codeload.github.com/thephpleague/fractal/legacy.zip/06dc15f6ba38f2dde2f919d3095d13b571190a7c
  - Applying patches for league/fractal (1)
    ~ laravel/laravel: patches/thephpleague/fractal/ReturnTypeWillChange.patch [NEW]
      fix ReturnTypeWillChange)
      Executing command (/builds/builder/backend/vendor/league/fractal): which patch
      The provided cwd "/builds/builder/backend/vendor/league/fractal" does not exist.
      #0 phar://usr/local/bin/composer/vendor/symfony/process/Process.php(252): Symfony\Component\Process\Process->start(Object(Closure), Array)
      #1 phar://usr/local/bin/composer/src/Composer/Util/ProcessExecutor.php(128): Symfony\Component\Process\Process->run(Object(Closure))
```

**Comment by beeyev** [comment]
I believe I found what causes the bug,
This is because I used `no-cache` flag during composer install `composer install --no-cache`
And I believe this is not a correct behavior for the patcher.

**Comment by jooname** [comment]
Apologies for getting back to you so late!

Managed to replicate this myself even with latest version of the package, Composer and PHP, so problem is definitely in the plugin. Looking at your output and the errors I got, the problem seems to be the same as in https://github.com/vaimo/composer-patches/issues/118. In that issue report, instead of `no-cache` flag, cache is just flushed before applying patches, which more or less achieves the same result.

The issue should be eventually solved by these PRs:

- https://github.com/vaimo/composer-patches/pull/124
- https://github.com/vaimo/composer-patches/pull/119

**Comment by beeyev** [comment]
Better too late than never 😊
Thank you!

**Comment by jooname** [comment]
Solution to this was now added in version 5.5.2 of the package!
