### ISSUE TITLE
Lost compatibility with composer 1.7.0

### ISSUE THREAD

**Issue by kassner** [vaimo/composer-patches#15]
After upgrading composer to 1.7.0, I get this error message:

```
root@82d8004a6dc2:/var/www/html# composer install -vvv
Reading ./composer.json
Loading config file /root/.composer/config.json
Loading config file /root/.composer/auth.json
Loading config file ./composer.json
Checked CA file /etc/ssl/certs/ca-certificates.crt: valid
Executing command (/var/www/html): git branch --no-color --no-abbrev -v
Executing command (/var/www/html): git describe --exact-match --tags
Executing command (/var/www/html): git log --pretty="%H" -n1 HEAD
Executing command (/var/www/html): hg branch
Failed to initialize global composer: Composer could not find the config file: /root/.composer/composer.json
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
Reading /var/www/html/vendor/composer/installed.json
Loading plugin MagentoHackathon\Composer\Magento\Plugin
activate magento plugin
Loading plugin Vaimo\ComposerPatches\Plugin
PHP Fatal error:  Uncaught Error: Class 'Tivie\OS\Detector' not found in /var/www/html/vendor/vaimo/composer-patches/src/Config/Context.php:19
Stack trace:
#0 /var/www/html/vendor/vaimo/composer-patches/src/Factories/ConfigFactory.php(31): Vaimo\ComposerPatches\Config\Context->__construct()
#1 /var/www/html/vendor/vaimo/composer-patches/src/Bootstrap.php(60): Vaimo\ComposerPatches\Factories\ConfigFactory->__construct()
#2 /var/www/html/vendor/vaimo/composer-patches/src/Plugin.php(31): Vaimo\ComposerPatches\Bootstrap->__construct(Object(Composer\Composer), Object(Composer\IO\ConsoleIO))
#3 phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(236): Vaimo\ComposerPatches\Plugin->activate(Object(Composer\Composer), Object(Composer\IO\ConsoleIO))
#4 phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(205): Composer\Plugin\PluginManager->addPlugin(Object(Vaimo\ComposerPatches\Plugin))
#5 phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(261): Composer\Plugin\PluginManager->register in /var/www/html/vendor/vaimo/composer-patches/src/Config/Context.php on line 19

Fatal error: Uncaught Error: Class 'Tivie\OS\Detector' not found in /var/www/html/vendor/vaimo/composer-patches/src/Config/Context.php:19
Stack trace:
#0 /var/www/html/vendor/vaimo/composer-patches/src/Factories/ConfigFactory.php(31): Vaimo\ComposerPatches\Config\Context->__construct()
#1 /var/www/html/vendor/vaimo/composer-patches/src/Bootstrap.php(60): Vaimo\ComposerPatches\Factories\ConfigFactory->__construct()
#2 /var/www/html/vendor/vaimo/composer-patches/src/Plugin.php(31): Vaimo\ComposerPatches\Bootstrap->__construct(Object(Composer\Composer), Object(Composer\IO\ConsoleIO))
#3 phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(236): Vaimo\ComposerPatches\Plugin->activate(Object(Composer\Composer), Object(Composer\IO\ConsoleIO))
#4 phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(205): Composer\Plugin\PluginManager->addPlugin(Object(Vaimo\ComposerPatches\Plugin))
#5 phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(261): Composer\Plugin\PluginManager->register in /var/www/html/vendor/vaimo/composer-patches/src/Config/Context.php on line 19
```

After deleting the `vendor` folder and trying again:

```
root@82d8004a6dc2:/var/www/html# composer install -vvv
Reading ./composer.json
Loading config file /root/.composer/config.json
Loading config file /root/.composer/auth.json
Loading config file ./composer.json
Checked CA file /etc/ssl/certs/ca-certificates.crt: valid
Executing command (/var/www/html): git branch --no-color --no-abbrev -v
Executing command (/var/www/html): git describe --exact-match --tags
Executing command (/var/www/html): git log --pretty="%H" -n1 HEAD
Executing command (/var/www/html): hg branch
Failed to initialize global composer: Composer could not find the config file: /root/.composer/composer.json
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
Running 1.7.0 (2018-08-03 15:39:07) with PHP 7.0.30-1+ubuntu16.04.1+deb.sury.org+1 on Linux / 4.9.93-linuxkit-aufs
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Reading ./composer.lock
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Reading ./composer.lock
Resolving dependencies through SAT
Looking at all rules.

[...]

  - Installing tivie/php-os-detector (1.1.0): Reading /root/.composer/cache/files/tivie/php-os-detector/3070e4f6c3d4c6ce53a8fd95019b01c10c30e8b6.zip from cache
Loading from cache
 Extracting archive    REASON: Required by the root package: Install command rule (install tivie/php-os-detector 1.1.0)

  - Installing vaimo/magento-composer-plugin (2.4.3): Reading /root/.composer/cache/files/vaimo/magento-composer-plugin/6f672e4a165b4e0ccf08de1913b254b0a42f1f50.zip from cache
Loading from cache
 Extracting archiveLoading plugin Vaimo\Magento\Plugin\Plugin
    REASON: Required by the root package: Install command rule (install vaimo/magento-composer-plugin 2.4.3)

  - Installing vaimo/composer-patches (3.27.0): Reading /root/.composer/cache/files/vaimo/composer-patches/de47e94f9956fa095e90bf2b3a7ae7278cd8148d.zip from cache
Loading from cache
 Extracting archiveLoading plugin Vaimo\ComposerPatches\Plugin
PHP Fatal error:  Uncaught Error: Class 'Tivie\OS\Detector' not found in /var/www/html/vendor/vaimo/composer-patches/src/Config/Context.php:19
Stack trace:
#0 /var/www/html/vendor/vaimo/composer-patches/src/Factories/ConfigFactory.php(31): Vaimo\ComposerPatches\Config\Context->__construct()
#1 /var/www/html/vendor/vaimo/composer-patches/src/Bootstrap.php(60): Vaimo\ComposerPatches\Factories\ConfigFactory->__construct()
#2 /var/www/html/vendor/vaimo/composer-patches/src/Plugin.php(31): Vaimo\ComposerPatches\Bootstrap->__construct(Object(Composer\Composer), Object(Composer\IO\ConsoleIO))
#3 phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(236): Vaimo\ComposerPatches\Plugin->activate(Object(Composer\Composer), Object(Composer\IO\ConsoleIO))
#4 phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(205): Composer\Plugin\PluginManager->addPlugin(Object(Vaimo\ComposerPatches\Plugin))
#5 phar:///usr/local/bin/composer/src/Composer/Installer/PluginInstaller.php(62): Composer\Plugin\PluginManager->regi in /var/www/html/vendor/vaimo/composer-patches/src/Config/Context.php on line 19

Fatal error: Uncaught Error: Class 'Tivie\OS\Detector' not found in /var/www/html/vendor/vaimo/composer-patches/src/Config/Context.php:19
Stack trace:
#0 /var/www/html/vendor/vaimo/composer-patches/src/Factories/ConfigFactory.php(31): Vaimo\ComposerPatches\Config\Context->__construct()
#1 /var/www/html/vendor/vaimo/composer-patches/src/Bootstrap.php(60): Vaimo\ComposerPatches\Factories\ConfigFactory->__construct()
#2 /var/www/html/vendor/vaimo/composer-patches/src/Plugin.php(31): Vaimo\ComposerPatches\Bootstrap->__construct(Object(Composer\Composer), Object(Composer\IO\ConsoleIO))
#3 phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(236): Vaimo\ComposerPatches\Plugin->activate(Object(Composer\Composer), Object(Composer\IO\ConsoleIO))
#4 phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(205): Composer\Plugin\PluginManager->addPlugin(Object(Vaimo\ComposerPatches\Plugin))
#5 phar:///usr/local/bin/composer/src/Composer/Installer/PluginInstaller.php(62): Composer\Plugin\PluginManager->regi in /var/www/html/vendor/vaimo/composer-patches/src/Config/Context.php on line 19
```

Weirdly, the class is available in `vendor/tivie/php-os-detector/src/Detector.php`, but I believe at this point the Plugin is not able to load a dependency that was just installed.

**Comment by allanpaiste** [comment]
Could you test if it works with the latest unreleased version?

```shell
composer self-update --snapshot
```

Browsed around at their issues and did find some similar issues being reported.
