### ISSUE TITLE
Uncaught Error: Call to a member function getRequires() on bool

### ISSUE THREAD

**Issue by loevgaard** [vaimo/composer-patches#57]
```
PHP Fatal error:  Uncaught Error: Call to a member function getRequires() on bool in /dev/code/vendor/vaimo/composer-patches/src/Patch/DefinitionList/LoaderComponents/ConstraintsComponent.php:62
Stack trace:
#0 /dev/code/vendor/vaimo/composer-patches/src/Patch/DefinitionList/Loader.php(62): Vaimo\ComposerPatches\Patch\DefinitionList\LoaderComponents\ConstraintsComponent->process(Array, Array)
#1 [internal function]: Vaimo\ComposerPatches\Patch\DefinitionList\Loader->Vaimo\ComposerPatches\Patch\DefinitionList\{closure}(Array, Object(Vaimo\ComposerPatches\Patch\DefinitionList\LoaderComponents\ConstraintsComponent))
#2 /dev/code/vendor/vaimo/composer-patches/src/Patch/DefinitionList/Loader.php(60): array_reduce(Array, Object(Closure), Array)
#3 /dev/code/vendor/vaimo/composer-patches/src/Repository/Processor.php(40): Vaimo\ComposerPatches\Patch\DefinitionList\Loader->loadFromPacka in /dev/code/vendor/vaimo/composer-patches/src/Patch/DefinitionList/LoaderComponents/ConstraintsComponent.php on line 62
```

I am getting the above error when I run `composer require vaimo/composer-patches`

**Comment by allanpaiste** [comment]
Note taken. I'd take this happens when you initially install the plugin or was it already present?

doing this with **--no-plugins** would probably help, but it's still a bug :)
